/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;

/**
 *
 * @author ASUS
 */
public class a10 extends javax.swing.JFrame {

    /**
     * Creates new form a10
     */
    public a10() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(1332, 728));
        setSize(new java.awt.Dimension(1280, 760));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/10.png"))); // NOI18N

        jTextPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 102)));
        jTextPane1.setFont(new java.awt.Font("TH Niramit AS", 0, 24)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(153, 51, 0));
        jTextPane1.setText("WHEEL OF FORTUNE\n\"วงล้อแห่งโชคชะตา ที่กำลังหมุนไป ส่งผลให้ชีวิตนั้นหมุนตามไปด้วย\"");
        jScrollPane1.setViewportView(jTextPane1);

        jTextPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 51)));
        jTextPane2.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(153, 102, 0));
        jTextPane2.setText("ไพ่ใบนี้เป็นไพ่ที่มีความหมายง่ายๆตรงๆ คือการเปลี่ยนแปลง แต่เวลาตีความจะตีได้ยาก เพราะเราไม่รู้เลยว่ามันหมุนไปทางไหน ดวงจะดีหรือร้าย ก็ไม่ทราบแน่ชัดครับ อาจต้องดูไพ่ประกอบ คือ ไพ่ทางซ้ายของไพ่วงล้อโชคชะตานี้ จะหมายถึงจุดเริ่มต้น อดีต หรือปัจจุบัน กำลังหมุนไปไพ่ทางขวาคือ สิ่งที่กำลังจะเปลี่ยนไปถึง หรืออนาคตนั่นเอง\n\nเนื่องจากไพ่ใบนี้เป็นไพ่ชุดใหญ่ การเปลี่ยนแปลงจึงเป็นสิ่งที่เราควบคุมได้ยาก เหมือนเป็นโชคชะตาจากฟ้าที่เรากำหนดไม่ได้\n\nความหมายในเรื่องความรัก\nความรักสำหรับไพ่ใบนี้ หมายถึงการเปลี่ยนแปลง เหมือนโชคชะตากำลังเปลี่ยนแปลงแล้ว ความสัมพันธ์ของคุณจะเปลี่ยนแปลงซึ่งคุณก็อาจจะคาดไม่ถึง\n\nถ้าถามว่าเปลี่ยนไปดีมั้ย โดยส่วนใหญ่ไพ่ใบนี้จะแปลว่า โชคดี ดังนั้นจึงหมายถึงความโชคดีในด้านความรัก โชคชะตาได้หมุนให้ความสัมพันธ์ของคุณไปในทางที่ดีแล้ว\n\nประเด็นคือ ไพ่ใบนี้มันไม่ได้บอกว่าดีเสมอไปครับ จึงเป็นไพ่ที่อ่านได้ยาก จำเป็นต้องมีไพ่ประกอบว่าทิศทางของโชคชะตากำลังหมุนไปทิศทางใด อาจเปิดไพ่เพิ่มเติมในกรณีที่เปิดได้ไพ่ใบนี้และถามว่า \"โชคชะตาจะเปลี่ยนไปยังไง\" หรือ ถ้าในกรณีการดูไพ่หลายใบ วงล้อในไพ่หมุนไปทางด้านขวา ไพ่ที่อยู่ด้านขวาก็เป็นเหมือนจุดหมายปลายทางของการหมุน ว่าจะหมุนไปทางไหนยังไง\n\nKEYWORD ของ ไพ่ยิปซี ใบนี้จึงคือ\n''การเปลี่ยนแปลงของโชคชะตา ที่เหนือการควบคุมของเรา...''");
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(jButton1))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
