/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;

/**
 *
 * @author ASUS
 */
public class a11 extends javax.swing.JFrame {

    /**
     * Creates new form a11
     */
    public a11() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(1332, 728));
        setSize(new java.awt.Dimension(1280, 760));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/11.png"))); // NOI18N

        jTextPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 153, 0)));
        jTextPane2.setFont(new java.awt.Font("TH Niramit AS", 0, 24)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(153, 102, 0));
        jTextPane2.setText("JUSTICE\n\"ผู้พิพากษาที่ตัดสินทุกอย่างด้วยความยุติธรรม มือขวาของเธอถือดาบพร้อมฟาดฟันตัดสิน มือซ้ายถือตาชั่งที่แสดงถึงความยุติธรรม เท่าเทียม ไม่โอนเอียง\"");
        jTextPane2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTextPane2);

        jTextPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        jTextPane1.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(204, 102, 0));
        jTextPane1.setText("ไพ่ใบนี้จะมีความหมายในลักษณะความยุติธรรม อะไรถูกก็คือถูก อะไรผิดก็คือผิด ตัดสินใจด้วยหลักเหตุผล ไม่ใช้อารมณ์ตัดสิน ไม่ลำเอียง เป็นการปรับสมดุลอย่างเท่าเทียมกัน คือการทำแล้วต้องได้ผลที่ทำอย่างเท่าเทียม ทำดีได้ดี ทำชั่วได้ชั่ว\n\nไพ่ใบนี้ถ้าเป็นลักษณะคน จะหมายถึงคนที่ตัดสินใจอย่างยุติธรรม ได้รับอะไรก็จะตอบแทนอย่างเท่าเทียม มีเหตุผล อาจหมายถึง ข้าราชการ ตำรวจ อัยการ ผู้พิพากษา หรือรวมๆคือผู้ที่มีอำนาจบังคับใช้กฏหมาย\n\nความหมายในเรื่องความรัก\nความรักของไพ่ใบนี้ ก็จะเน้นไปที่ความเท่าเทียม การตัดสินใจด้วยเหตุผล มีการแลกเปลี่ยนความรักกันอย่างเท่าเทียม อาจมองได้ทั้งดีไม่ดี แต่ถ้าใบนี้ขึ้นย่อมหมายถึงสิ่งที่ดีกับเราแน่นอน เพราะมันเป็นการตัดสินใจที่มีเหตุผล เช่น\n\nเค้ารักเรา เรารักเค้า เราทำเพื่อเค้า เค้าก็ทำเพื่อเรา จะมีความเท่าเทียมในความรัก\nเค้าไม่สนใจเรา ความสัมพันธ์ที่เราให้ฝ่ายเดียว ถ้าไพ่ใบนี้ขึ้นก็จะหมายความว่า เราเริ่มตัดสินใจแล้วล่ะว่า เรายังโอเคมั้ย ทำไมเค้าไม่ตอบรับอะไรเรากลับมา... ถ้าเราไม่โอเค เราก็ก้าวออกมาจากความสัมพันธ์ที่ทำร้ายจิตใจเราออกมา\nความสัมพันธ์ที่ยังฝืนต่อไป แม้มันจะไม่ดีต่อใจ ถ้าได้ไพ่ใบนี้ เราก็พร้อมจะตัดสินใจที่จะจัดการทุกอย่างให้มันโอเคขึ้น ตัดสินใจที่พูดคุย เคลียร์ จนถึงการเดินจากกันไป\nไพ่ใบนี้จึงเน้นความหมายไปที่การลดความขัดแย้งในใจ   ความซับซ้อนในความสัมพันธ์ ถ้าไพ่ใบนี้ขึ้น ก็คือถึงเวลาแล้วที่คุณจะตัดสินใจด้วยการคิดวิเคราะห์แล้วว่า คุณจะเดินหน้าความสัมพันธ์ต่อมั้ย หรือจะเดินจากไป แน่นอนว่าเป็นการตัดสินใจที่ใช้เหตุผล ความถูกต้อง ในการตัดสินใจ\n\nหากคุณคิดจะเดินหน้าต่อไป ก็อาจหมายถึงการปรับใจ ปรับความสัมพันธ์ให้มันเท่าเทียมกัน เช่น คนขี้หึงมากๆ โดยไม่มีเหตุผลนัก ก็จะต้องลดระดับความขี้หึง ให้บาลานซ์กัน เพื่อให้ความสัมพันธ์ราบรื่นก็เป็นได้\n\nKEYWORD ของ ไพ่ยิปซี ใบนี้จึงคือ\n''การตัดสินใจ ปรับสมดุลลดความขัดแย้งในใจ ให้เกิดความเท่าเทียมยุติธรรม...''");
        jTextPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(jButton1))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane1AncestorAdded
        jTextPane1.setEditable(false);
    }//GEN-LAST:event_jTextPane1AncestorAdded

    private void jTextPane2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane2AncestorAdded
        jTextPane2.setEditable(false);
    }//GEN-LAST:event_jTextPane2AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
