/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;

/**
 *
 * @author ASUS
 */
public class a12 extends javax.swing.JFrame {

    /**
     * Creates new form a12
     */
    public a12() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(1332, 728));
        setSize(new java.awt.Dimension(1280, 760));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/12.png"))); // NOI18N

        jTextPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 153, 0)));
        jTextPane1.setFont(new java.awt.Font("TH Niramit AS", 0, 24)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(153, 102, 0));
        jTextPane1.setText("THE HANGED MAN\n\"ชายผู้ถูกห้อยหัว ให้ทรมาน แต่ท่าทางของเขากลับทำให้รู้ว่าเขาไม่เป็นไร ด้วยขาที่ขัดกันเป็นเลข 4 ซึ่งมีความหมายถึงความสมดุล สงบนิ่ง และแสงล้อมรอบหัวหมายถึงการตระหนักรู้\"");
        jTextPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        jTextPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));
        jTextPane2.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(153, 0, 0));
        jTextPane2.setText("ไพ่ใบนี้โดยปกติคนมักจะแปลกันไม่ค่อยดีเท่าไหร่นัก เพราะเป็นไพ่ของชายที่ถูกทรมานโดยการห้อยหัว แต่จริงๆแล้ว ไพ่ใบนี้ค่อนข้างจะมีความหมายที่ดีในระดับนึง เพราะตัวชายคนนี้โอเคที่จะถูกห้อยหัว และการห้อยหัวทำให้เค้าสามารถมองมุมใหม่ๆ จนตระหนักรู้อะไรบางอย่างได้\n\nดังนั้นไพ่ใบนี้โดยปกติจะหมายถึง การที่เราพัก หรือทนทรมานกับเรื่องบางอย่าง แต่เราก็รับได้ แล้วก็ทำให้เราได้เรียนรู้ ได้ตระหนักรู้อะไรบางอย่างขึ้นมาด้วย\n\nความหมายในเรื่องความรัก\nความรักของไพ่ใบนี้ออกจะเป็นแนว ถ้าคบกันอยู่ก็จะเป็นการเสียสละ ยอมทน เพื่อความสัมพันธ์จะได้ดำเนินต่อไป เช่น ความรักข้างเดียว ความรักที่เค้าไม่ชอบตอบ ความไม่ชัดเจน หรือความรักที่เป็นแฟนกันแล้วอีกฝ่ายมีข้อเสียมากมาย แล้วเราก็พร้อมที่จะรักและอยู่กับเค้าคนนั้นได้ แม้จะทรมาน แต่ก็โอเค\n\nไพ่ใบนี้อาจหมายถึงการพัก เว้นระยะหรือห่างๆกันได้อีกด้วย ซึ่งจะมีลักษณะคล้ายการรอ ในกรณีที่อีกฝ่ายต้องการระยะห่าง เวลาส่วนตัวบ้าง หรือห่างหายไปบ้าง ซึ่งคนที่ได้ไพ่ใบนี้ก็จะรอ รอทรมาน คิดถึง ทนไป เหมือนคนห้อยหัว แต่ก็เข้าใจดีว่าอีกฝ่ายต้องการความห่างนี้\n\nในกรณีที่เลิกกัน ก็อาจหมายความได้ว่า อาจมีความเจ็บปวดทรมานในใจที่เลิกกัน แต่ก็เข้าใจดี และซักวันมันก็คงหายดีได้\n\nKEYWORD ของ ไพ่ยิปซี ใบนี้จึงคือ\n''ความเจ็บที่เข้าใจได้ อดทนได้ ความทรมานที่ทำให้ได้เห็นมองมุมใหม่ ได้เรียนรู้...''");
        jTextPane2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(jButton1))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPane2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane2AncestorAdded
        jTextPane1.setEditable(false);
    }//GEN-LAST:event_jTextPane2AncestorAdded

    private void jTextPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane1AncestorAdded
        jTextPane2.setEditable(false);
    }//GEN-LAST:event_jTextPane1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a12().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
