/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;

/**
 *
 * @author ASUS
 */
public class a13 extends javax.swing.JFrame {

    /**
     * Creates new form a13
     */
    public a13() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(1332, 728));
        setSize(new java.awt.Dimension(1280, 760));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/13.png"))); // NOI18N

        jTextPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 51, 255)));
        jTextPane1.setFont(new java.awt.Font("TH Niramit AS", 0, 24)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(153, 51, 0));
        jTextPane1.setText("DEATH\n\"ยมทูตผู้มอบความตายแก่ทุกคนไม่เว้นแม้แต่จักรพรรดิ ได้เดินทางมาเพื่อจะมอบความตายให้แม่และเด็ก แต่ทว่าพระสังฆราชได้มาเจรจาให้หยุดยั้งไว้\"");
        jScrollPane1.setViewportView(jTextPane1);

        jTextPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 204)));
        jTextPane2.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(153, 51, 0));
        jTextPane2.setText("ไพ่ใบนี้เป็นไพ่ที่ปกติคนมักจะตกใจและกลัวเพราะมันหมายถึงเกี่ยวกับความตาย แต่อันที่จะจริงแล้ว ความหมายของมันคือการเปลี่ยนแปลง การจบบางสิ่งเพื่อเริ่มใหม่ โดยความหมายจะดีหรือไม่ดี ก็แล้วแต่สถานการณ์และไพ่อื่นๆประกอบ\n\nแต่ถ้าดูตามเนื้อความของไพ่แล้วจะพบว่า พระสังฆราชได้มาหยุดยั้งการนำพาความตายของยมทูตไว้ นั่นก็หมายความว่าสิ่งที่ไม่ดีที่ผ่านมามันกำลังจะจบลงก็ได้ครับ\n\nไพ่ใบนี้อาจหมายถึง การเดินทางไปต่างประเทศ การไปโรงพยาบาล หรือสถานที่ที่คนตายได้ครับ\n\nความหมายในเรื่องความรัก\nไพ่ใบนี้มักหมายถึงการเปลี่ยนแปลงในความสัมพันธ์ เป็นการจบสถานะบางอย่างไปสู่สถานะใหม่ แน่นอนว่าเป็นความหมายที่ดี หรือไม่ดีก็ได้ครับ เช่น\n\nจากที่คุยๆไม่ชัดเจนกัน ก็ชัดเจนขึ้นมา\nจากที่เป็นแฟนกัน ก็อาจจะหมายถึงการหมดความรักต่อกันก็ได้\nความหมายจึงค่อนข้างตีความได้ยากว่า จะจบและเริ่มต้นสิ่งใหม่ในทางที่ดี หรือไม่ดี ก็ต้องดูว่าที่ผ่านมาสถานการณ์ความสัมพันธ์เป็นอย่างไรครับ หรือถ้าเราดูไพ่หลายใบก็ดูไพ่ประกอบ ดูในทิศทางที่ม้าเคลื่อนไป ม้ายมทูตเคลื่อนไปทางทิศไหน ไพ่ที่อยู่ทิศนั้นก็คือคำตอบของการเปลี่ยนแปลงได้\n\nโดยส่วนตัวผมมองว่าไพ่ใบนี้ค่อนข้างดี ครับ เพราะว่ามันหมายถึงการเปลี่ยนแปลง การเปลี่ยนแปลงไปในทางที่ดีย่อมหมายถึง การพัฒนาความสัมพันธ์ไปอีกขั้น ก็ได้ครับ หรือถ้าในกรณีที่เราค่อนข้างมีเรื่องกลุ่มใจ ความสัมพันธ์ที่ไม่ดี เพราะอะไรที่มันไม่ดีกำลังจะจบไป ดวงอาทิตย์ที่สดใสก็กำลังขึ้นอยู่ข้างหน้าแล้วครับ\n\nแต่ถ้าถามว่าในกรณีเค้าคนนั้นจะกลับมามั้ย ก็เป็นไปได้ว่าจะกลับมาแต่ก็คงไม่เหมือนเดิมครับ อาจจะเป็นได้แค่เพื่อน อาจจะหมดรักไปแล้วครับ\n\nKEYWORD ของ ไพ่ยิปซี ใบนี้จึงคือ\n''การเปลี่ยนแปลงไปสู่สิ่งใหม่ การจบสิ่งที่เป็นอยู่เพื่อเริ่มต้นใหม่...''");
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(jButton1))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a13().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
