/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;

/**
 *
 * @author ASUS
 */
public class a14 extends javax.swing.JFrame {

    /**
     * Creates new form a14
     */
    public a14() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(1332, 728));
        setSize(new java.awt.Dimension(1280, 760));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/14.png"))); // NOI18N

        jTextPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 102)));
        jTextPane1.setFont(new java.awt.Font("TH Niramit AS", 0, 24)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(153, 51, 0));
        jTextPane1.setText("TEMPERANCE\n\"เทวดาผู้ที่ยืนอยู่ตรงริมฝั่ง เท้าข้างนึงอยู่ในน้ำ เท้าข้างนึงอยู่บนพื้นดิน  กำลังทำการทดลองผสมน้ำจากถ้วยสองถ้วย ถ้วยนึงเย็น ถ้วยนึงร้อน เข้าด้วยกัน\"");
        jTextPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        jTextPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 153)));
        jTextPane2.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(153, 51, 0));
        jTextPane2.setText("ไพ่ใบนี้ถ้าดูจากรูป เทวดาไม่ก้าวลงน้ำซะทีเดียว ขาข้างนึงยังอยู่บนบกอยู่ นั่นหมายความว่าเป็นการที่ยัง ไม่ตัดสินใจ การที่ยังดูสถานการณ์อยู่ หรือกำลังปรับตัว ทดลอง อยู่ ดังภาพที่เทวดาผสมถ้วยสองถ้วยที่แตกต่างเข้าด้วยกัน เป็นการหา สมดุล ระหว่างสิ่งต่างๆที่ตรงข้ามกันในสถานการณ์นั้นๆ\n\nความหมายในเรื่องความรัก\nไพ่ใบนี้ในด้านความรักจะหมายถึง การที่เราหา สมดุลในความสัมพันธ์ เช่น บางทีเราความรู้สึกอาจมากเกินไป การกระทำอาจจะมากเกินไป ทำให้อีกฝ่ายอึดอัด เราก็จะต้องถอยออกมาค่อยๆเป็นค่อยๆไป ทดลองปรับตัวให้อยู่ตรงกลาง ให้ความสัมพันธ์ดำเนินไปได้ด้วยดี\n\nอาจหมายถึงการที่เรากำลังปรับตัวเองยอมรับในข้อเสียของอีกฝ่ายก็ได้\n\nในกรณีที่โสด ถ้าไพ่ใบนี้ขึ้นก็อาจจะหมายความว่าอยู่ในช่วงการ ทดลอง คุยกัน การปรับตัวเข้าหากัน ซึ่งใบนี้มันก็จะออกความรู้สึก กล้าๆ กลัวๆ ซักนิดหน่อย เพราะยังไม่มั่นใจในอะไรบางอย่าง เลยต้องทดลองคุยดู\n\nลักษณะของไพ่ใบนี้จึงเน้นไปในแนว การที่เราทดลอง ปรับสมดุล ในความสัมพันธ์ให้ทุกสิ่งอย่างดำเนินออกไปได้ด้วยดี ทั้งด้านอารมณ์ และสิ่งต่างๆภายนอก (ดังจะเห็นว่าเท้าข้างนึงอยู่ใน้น้ำ ซึ่งน้ำหมายถึงอารมณ์ หรือสิ่งที่อยู่ภายในจิตใจ เท้าข้างนึงอยู่บนพื้นดิน ซึ่งดินหมายถึงสิ่งภายนอก วัตถุ)\n\nKEYWORD ของ ไพ่ยิปซี ใบนี้จึงคือ\n''การทดลอง การปรับหาสมดุลในความสัมพันธ์...''\n");
        jTextPane2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(jButton1))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPane2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane2AncestorAdded
        jTextPane1.setEditable(false);
    }//GEN-LAST:event_jTextPane2AncestorAdded

    private void jTextPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane1AncestorAdded
        jTextPane2.setEditable(false);
    }//GEN-LAST:event_jTextPane1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a14().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
