/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;

/**
 *
 * @author ASUS
 */
public class a15 extends javax.swing.JFrame {

    /**
     * Creates new form a15
     */
    public a15() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(1332, 728));
        setSize(new java.awt.Dimension(1280, 760));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/15.png"))); // NOI18N

        jTextPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 153)));
        jTextPane1.setFont(new java.awt.Font("TH Niramit AS", 0, 24)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(153, 51, 0));
        jTextPane1.setText("THE DEVIL\n\"ปีศาจผู้ควบคุมให้คนสองคน ชายและหญิงมาผูกมัดกันด้วยโซ่ แต่ทว่าโซ่ที่มัดหลวมนี้อันที่จริงไม่ได้ผูกมัดทั้งสองคนไว้ แต่เป็นสิ่งที่อยู่ลึกลงไปในจิตใจที่ทำให้คนสองคนยังผูกติดกันอยู่\"");
        jTextPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        jTextPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        jTextPane2.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(153, 102, 0));
        jTextPane2.setText("THE DEVIL\n\"ปีศาจผู้ควบคุมให้คนสองคน ชายและหญิงมาผูกมัดกันด้วยโซ่ แต่ทว่าโซ่ที่มัดหลวมนี้อันที่จริงไม่ได้ผูกมัดทั้งสองคนไว้ แต่เป็นสิ่งที่อยู่ลึกลงไปในจิตใจที่ทำให้คนสองคนยังผูกติดกันอยู่\"\n\nความหมายในเรื่องความรัก\nโดยปกติไพ่ใบนี้ ถ้าแปลกันในหลายๆที่จะแปลถึง การมีชู้ การรักสามเส้า การนอกใจ การผิดศีล การโกหกหลอกลวง อันที่จริงที่แปลอย่างนี้เพราะไพ่มีความหมายถึงการหลงมัวเมา ดังนั้นก็เป็นไปได้ว่าจะไปหลงคนอื่น ซึ่งจริงๆมันก็เป็นไปได้ว่า เค้ามีสิ่งที่เค้าหลงใหลมากกว่าคุณ เช่น งาน กีฬา เกมส์ ก็เป็นได้\n\nแต่ถ้าไพ่ประกอบใบอื่นๆขึ้นมาชัดว่าไม่ได้มีคนอื่น และเป็นไพ่ที่บอกลักษณะของความสัมพันธ์ที่คุณสองคนรักกันอยู่แล้ว ก็แปลได้ว่า คุณสองคนมีบางอย่างลึกๆที่ทำให้ผูกมัดกันอยู่ ชื่นชอบหลงใหลกันด้วยเรื่องภายนอก เช่น ชื่นชอบการด้วยหน้าตา เซ็กส์ หรือแม้กระทั่งเงิน ซึ่งมันก็เป็นความรักในรูปแบบนึงเช่นกัน ไม่ใช่เรื่องผิดอะไร\n\nในกรณีที่ความสัมพันธ์ไม่ได้ราบรื่น ดูน่าจะยุติความสัมพันธ์กันแล้ว แต่มันก็ยังเลิกกันไม่ได้ซักที ไพ่ใบนี้ก็บอกได้ว่า คุณสองคนยังมีอะไรลึกๆที่ผูกมัดกันอยู่ ทำให้ไม่ขาดจากกัน รวมไปถึงอาจเป็นกรรมเก่าที่คุณสองคนทำไว้ในอดีตก็เป็นได้ ทำให้บางทีการแปลก็จะแปลว่า ขาดแยกจากกันยาก เป็นไพ่ที่อาจจะบอกได้ว่าคุณเป็น คู่กัน แต่เป็น คู่กรรม กัน หากจะให้ดีให้ร่วมกันทำบุญทำทาน ทำจิตใจให้สงบ ถือศีล ความสัมพันธ์ก็จะกลายเป็นดีได้ครับ\n\nอาจหมายถึงสิ่งที่แบกไว้ในอดีต กรรมในอดีต ความยึดติดในอดีต เช่น ความรักกับคนรักเก่าที่ไม่ดี ส่งผลให้ไม่สามารถเดินหน้าต่อไปได้ เหมือนยังมีโซ่ผูกไว้กับคนเก่าที่ผ่านไปแล้วอยู่\nไพ่ใบนี้ผมจึงมองว่าไม่ใช่ไพ่ไม่ดี ความหมายดูเป็นไปในทางหลงใหล ยึดติดก็จริง แต่เพราะความยึดติดนี้ก็เป็นความรักอย่างนึงเหมือนกัน เพราะความยึดติดนี้ที่ทำให้เรายังคงความสัมพันธ์ไว้ แน่นอนว่ามันไม่ดีตรงที่ มันไม่ดีกับใจ อยู่ที่ว่าเมื่อไหร่ที่คุณพร้อมจะเป็นอิสระจากสิ่งนี้ได้เท่านั้น\n\nKEYWORD ของ ไพ่ยิปซี ใบนี้จึงคือ\n''ความหลงใหล ความมัวเมา หรือกรรมที่ทำไว้ทำให้ยังผูกติดกันแม้จะเป็นความสัมพันธ์ที่ไม่ดีก็ตาม...\"");
        jTextPane2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(jButton1))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPane2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane2AncestorAdded
        jTextPane1.setEditable(false);
    }//GEN-LAST:event_jTextPane2AncestorAdded

    private void jTextPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane1AncestorAdded
        jTextPane2.setEditable(false);
    }//GEN-LAST:event_jTextPane1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a15().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
