/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;

/**
 *
 * @author ASUS
 */
public class a16 extends javax.swing.JFrame {

    /**
     * Creates new form a16
     */
    public a16() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(1332, 728));
        setSize(new java.awt.Dimension(1280, 760));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/16.png"))); // NOI18N

        jTextPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 51, 0)));
        jTextPane1.setFont(new java.awt.Font("TH Niramit AS", 0, 24)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(153, 51, 0));
        jTextPane1.setText("THE TOWER\n\"หอคอยที่สร้างอยู่บนยอดเขา อันไม่มั่นคง โดนฟ้าผ่าพังทลายลงมา คนสองคนจึงต้องกระโดดหนีตาย ลงมาจากหอคอยนั้น โดยไม่แน่ใจว่าเบื้องล่างจะเป็นพื้นดิน หรือน้ำ\"");
        jTextPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        jTextPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 153, 0)));
        jTextPane2.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(153, 51, 0));
        jTextPane2.setText("ไพ่หอคอยใบนี้ โดยปกติก็มักจะแปลในทางที่ไม่ดีนัก เพราะไพ่มันเกี่ยวกับการพัง การเกิดภัยพิบัติ การเกิดอุบัติเหตุ แต่ไพ่ใบนี้จริงๆโดยหลักรวมๆแล้วแปลว่า การเปลี่ยนแปลง สิ่งที่เราสร้างขึ้นมาได้พังลง\n\nถ้าดูจากตัวไพ่หอคอย หอคอยนี้ได้ถูกสร้างขึ้นมาบนพื้นที่ที่ไม่ควรสร้างเท่าไหร่นัก มันไม่มันคง สิ่งที่เราสร้างขึ้นมาอย่างไม่มั่นคง มันกำลังพังลงอย่างรวดเร็ว ไม่ว่าจะความสัมพันธ์ ความรัก หรือรวมไปถึงพวกความกังวล ความคิดต่างๆที่เราสร้างขึ้นมา (แม้แต่กรรม หรือ โซ่จาก The Devil ก็ด้วย) กำลังพังลงอย่างฉับพลัน แล้วเราต้องออกมาจากสิ่งนั้นแล้ว\n\nดังนั้นไพ่ใบนี้จะมองว่าดีหรือไม่ดีก็ได้ อยู่ที่ไพ่ประกอบใบอื่นๆ หรือสถานการณ์ตอนนั้น\n\nความหมายในเรื่องความรัก\nไพ่ใบนี้ในมุมมองความรัก ก็จะเป็นอะไรที่เรียกได้ว่า การเปลี่ยนแปลงกระทันหัน\nความสัมพันธ์ก็อาจจะเปลี่ยนแปลงไปในทางที่ดีขึ้น หรือทางที่ไม่ดีก็ได้ แล้วแต่ไพ่ประกอบอื่นๆและสถานการณ์เป็นหลักครับ\n\nแต่ว่าส่วนใหญ่ไพ่ใบนึงมักจะมองในทางลบ เพราะจะหมายความว่า การแตกหัก แยกย้าย กระทันหันได้ โดยเฉพาะความสัมพันธ์ที่เริ่มมาไม่ดี หรือไม่มั่นคง หรืออาจจะเกิดการเปลี่ยนใจกระทันหัน เช่น มีนัด ก็อาจต้องยกเลิกนัดกระทันหัน ความสัมพันธ์กำลังจะดีก็กลับไปแย่อีกครั้งก็ได้\n\nสำหรับความหมายที่ดีของไพ่ใบนี้ดีก็เป็นได้เช่นกัน เช่น จากความสัมพันธ์ที่ไม่ดีก็อาจจะอยู่ดีๆ ก็ดีขึ้นมาโดยไม่ทันตั้งตัว หรือความสัมพันธ์แย่ ทำให้ต้องเครียดกังวล ความเครียดกังวลนั้นก็อาจจะพังทลายลงหายไปได้ครับ\n\nKEYWORD ของ ไพ่ยิปซี ใบนี้จึงคือ\n''การเปลี่ยนแปลงกระทันหัน การพังทลายของสิ่งที่สร้างอย่างไม่มั่นคง...\"");
        jTextPane2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(jButton1))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPane2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane2AncestorAdded
        jTextPane1.setEditable(false);
    }//GEN-LAST:event_jTextPane2AncestorAdded

    private void jTextPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane1AncestorAdded
        jTextPane2.setEditable(false);
    }//GEN-LAST:event_jTextPane1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a16().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
