/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;

/**
 *
 * @author ASUS
 */
public class a17 extends javax.swing.JFrame {

    /**
     * Creates new form a17
     */
    public a17() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(1332, 728));
        setSize(new java.awt.Dimension(1280, 760));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/17.png"))); // NOI18N

        jTextPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 51, 0)));
        jTextPane1.setFont(new java.awt.Font("TH Niramit AS", 0, 24)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(153, 102, 0));
        jTextPane1.setText("THE STAR\n\"แสงจากดวงดาวอันสุกใส ส่องให้เห็น หญิงสาวที่ริมน้ำ เธอเทโหลใส่น้ำสองใบ ใบนึงเทไปบนพื้นดินก่อให้เกิดการกำเนิดต้นไม้มากมาย  ใบนึงเทลงในน้ำเพื่อเติมเต็มและก่อให้เกิดการหมุนเวียน\"");
        jTextPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        jTextPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 0)));
        jTextPane2.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(153, 102, 0));
        jTextPane2.setText("ไพ่ใบนี้เป็นไพ่เป็นไพ่แห่งดวงดาวที่ส่องสว่างเป็น ความหวัง การเริ่มต้นใหม่ ผู้หญิงในไพ่ที่เปลื้องผ้าที่แสดงถึงความบริสุทธิ์ เท้าข้างนึงอยู่ในน้ำ ซึ่งน้ำแสดงถึงอารมณ์ความรู้สึก แสดงถึงการที่เป็นคนที่สามารถรับรู้ถึงอารมณ์ตัวเองได้ดี เธอคนนี้กำลังฟื้นฟูแหล่งน้ำ และพื้นดิน ให้กลับมาอุดมสมบูรณ์ เกิดใหม่\n\nถ้าหากดูไพ่ใบนี้เป็นเหมือนแสงที่ส่องทาง ให้ความหวัง ไพ่ใบนี้ยังหมายถึงการฟื้นฟูสภาพจิตใจ อารมณ์ ไปในทางที่ดีขึ้นได้อีกด้วย จากการที่เธอในรูปเทน้ำเพื่อฟื้นฟูพื้นดิน (สภาพภายนอก) และน้ำ (สภาพจิตใจ)\n\nความหมายในเรื่องความรัก\nด้านความรักไพ่ใบนี้ บ่งบอกถึงความหวัง ในสิ่งใหม่ๆ โดยเฉพาะถ้าเป็นความสัมพันธ์ที่พึ่งเริ่มต้นใหม่ ก็จะเป็นความสัมพันธ์ที่ดีและสมหวังได้ตามแสงของดาว\n\nถ้าเป็นในความสัมพันธ์ที่ไม่ดีหรือที่ผ่านมาความสัมพันธ์ค่อนข้างจะแย่ ไพ่ใบนี้ก็จะหมายความว่า ถึงเวลาแล้วที่เราจะต้อง ฟื้นฟูรักษาตัวเองให้ดี เพราะความสดใส ความหวังใหม่ๆ กำลังรอคอยเราอยู่ข้างหน้า หรือถ้าใครที่เจ็บมาก่อน เจ็บมาเยอะ อกหักมา ก็อาจจะเป็นช่วงเวลาที่ยังไม่คิดจะเริ่มอะไรที่วุ่นวายตอนนี้ ยังอยากจะรักษาตัวเอง รักษาบาดแผลให้หายดีซะก่อน\n\nไพ่ใบนี้มักจะแทนตัวผู้หญิง ดังนั้นถ้าผู้หญิงเป็นคนจับได้ใบนี้หรือถามว่าผู้ชายรู้สึกยังไงกับเราแล้วเราได้ใบนี้ ผู้ชายก็จะมองเราเป็นคนที่ดี จิตใจดี บริสุทธิ์ และสามารถดูแลห่วงใยเค้าได้ดี\n\nKEYWORD ของ ไพ่ยิปซี ใบนี้จึงคือ\n''ความหวังที่ส่องประกาย การดูแลฟื้นฟูสภาพร่างกายและจิตใจเพื่ออนาคตที่สดใสข้างหน้า...\"\n");
        jTextPane2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(jButton1))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPane2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane2AncestorAdded
        jTextPane1.setEditable(false);
    }//GEN-LAST:event_jTextPane2AncestorAdded

    private void jTextPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane1AncestorAdded
        jTextPane2.setEditable(false);
    }//GEN-LAST:event_jTextPane1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a17().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
