/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;

/**
 *
 * @author ASUS
 */
public class a18 extends javax.swing.JFrame {

    /**
     * Creates new form a18
     */
    public a18() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(1332, 728));
        setSize(new java.awt.Dimension(1280, 760));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/18.png"))); // NOI18N

        jTextPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 0, 102)));
        jTextPane1.setFont(new java.awt.Font("TH Niramit AS", 0, 24)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(153, 102, 0));
        jTextPane1.setText("THE MOON\n\"แสงจากดวงจันทร์ ที่สะท้อนมาจากแสงอาทิตย์ ได้เปิดเผยความมืดมิดที่ปิดบังไว้ ความกังวล ความกลัว หลายสิ่งหลายอย่างที่เก็บซ่อนไว้ภายในกำลังจะเปิดเผยขึ้นมา\"");
        jTextPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        jTextPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 0)));
        jTextPane2.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(153, 51, 0));
        jTextPane2.setText("ไพ่ใบนี้เป็นไพ่ที่เกี่ยวกับอารมณ์โดยตรง ความรู้สึกที่ซ่อนเร้นไว้ในความมืด ซ่อนไว้ใต้อารมณ์คล้ายกุ้งแม่น้ำที่คลานขึ้นมาจากในน้ำ ก็จะเปิดเผยขึ้นมา เช่น ความกลัว ความกังวล และความรู้สึกไม่ปลอดภัย เหมือนหมาป่าในรูปที่ปกติจะหลบซ่อนในความมืด แต่ถูกแสงจันทร์สว่างทำให้ ศัตรูอาจเห็นได้ง่าย\n\nความหมายในเรื่องความรัก\nไพ่ใบนี้ในเชิงความรัก ค่อนข้างเป็นไพ่ที่อ่อนไหวจริงๆ มันมีบางอย่างที่ผุดเปิดเผยขึ้นมาในความสัมพันธ์ เช่น เราไปรับรู้อะไรบางอย่างเกี่ยวกับเค้า ที่ทำให้เรารู้สึกไม่มั่นคง ซึ่งจริงๆมันอาจจะไม่ได้เป็นอย่างนั้นก็ได้ (เนื่องจากไพ่เป็นเพียงแค่แสงสลัว บางทีเราแค่ได้รับข่าวบางอย่าง เราก็มโนไปต่างๆนานา) หรือแม้แต่บางอย่างที่เราเก็บไว้ในใจ ความรู้สึกที่เราเก็บไว้ในใจมันลอยขึ้นมาเหนือผิวน้ำ ให้เราได้กังวล ก็เป็นได้\n\nโดยปกติไพ่ใบนี้เป็นเรื่องที่เกี่ยวกับอารมณ์ ดังนั้นจึงไม่ใช่เรื่องที่จะแก้ไขไม่ได้หรือว่าเลวร้าย เราสามารถปรับอารมณ์เรา ควบคุมอารมณ์เราได้ ลดการคิดมากคิดเยอะของเราลงได้ เพื่อให้ความสัมพันธ์มันดีขึ้น เพราะบางเรื่องเรามโนไปเอง มันก็จะทำให้อะไรต่างๆแย่ลงได้ครับ เป็นไพ่ที่ถ้าออกมาก็ควรจะหาข้อมูล ข่าว อะไรให้ถูกต้องหรืออาจถามเพื่อความชัดเจนไปเลยก็ได้ หากเรากังวลคิดมากจนทนไม่ไหว\n\nไพ่ใบนี้ยังอาจหมายถึง ความรู้สึกอ่อนไหว ความรู้สึกคิดถึง หรือเป็นได้ได้ว่า ผู้หญิง ที่ไพ่ใบนี้ขึ้นเป็นใบแทนกำลังอยู่ในช่วงประจำเดือน\n\nKEYWORD ของ ไพ่ยิปซี ใบนี้จึงคือ\n''ความกังวล ความรู้สึกอ่อนไหว ความรู้สึกไม่ปลอดภัยในความสัมพันธ์...\"");
        jTextPane2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPane2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane2AncestorAdded
        jTextPane1.setEditable(false);
    }//GEN-LAST:event_jTextPane2AncestorAdded

    private void jTextPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane1AncestorAdded
        jTextPane2.setEditable(false);
    }//GEN-LAST:event_jTextPane1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a18.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a18.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a18.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a18.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a18().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
