/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;

/**
 *
 * @author ASUS
 */
public class a19 extends javax.swing.JFrame {

    /**
     * Creates new form a19
     */
    public a19() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(1332, 728));
        setSize(new java.awt.Dimension(1280, 760));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/19.png"))); // NOI18N

        jTextPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 0)));
        jTextPane1.setFont(new java.awt.Font("TH Niramit AS", 0, 24)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(153, 102, 0));
        jTextPane1.setText("THE SUN\n\"ดวงอาทิตย์อันสดใส ส่องแสงสว่างไปยังทุกแห่งหน เด็กน้อยผู้นำความร่าเริงถือธงสีแดงบนม้ากำลังเข้ามา เบื้องหลังเป็นดอกทานตะวันที่บ่งบอกถึงความหวัง\"");
        jTextPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        jTextPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 51)));
        jTextPane2.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(102, 51, 0));
        jTextPane2.setText("ไพ่ใบนี้ถ้าจะให้ดูถือว่าเป็นไพ่ที่ผมคิดว่าดีที่สุดในไพ่ 22 ใบ เลยก็ว่าได้ โดยเฉพาะในด้านความคิด อารมณ์ ไพ่ใบนี้เปรียบเสมือนแสงอาทิตย์ที่ส่องสว่าง ให้ความสดใสแก่ทุกชีวิต ไพ่จึงหมายถึง ความสุข ความร่าเริง ความแจ่มใส ทุกๆอย่างกำลังเป็นไปในทางที่ดี และตัวดอกทานตะวันที่หมายถึงความหวัง ทำให้ไพ่ใบนี้ดูสดใสขึ้นไปอีก\n\nไพ่ใบนี้ยังเหมือนแสงสว่างที่ส่องไปยังพื้นที่ที่มืดมิด ทำให้เรามองเห็นอะไรที่ชัดเจนขึ้น จึงมีความหมายถึง การเปิดเผย การสะสาง สิ่งที่ปิดบัง ขุ่นมัว ได้ เช่น ความลับที่ถูกเปิดเผย เรื่องที่กังวลใจจะได้รับการคลี่คลาย\n\nความหมายในเรื่องความรัก\nไพ่ใบนี้ในเรื่องความรักก็สดใส ซาบซ่าน ล่ะครับ ความสัมพันธ์เป็นความสัมพันธ์ที่มีความหวัง มีความมุ่งมั่น ธงสีแดงที่หมายถึงความปรารถนา ที่จะประสบผลสำเร็จและราบรื่น\n\nถ้าความสัมพันธ์ของคนสองคนที่ไม่เข้าใจกัน ทะเลาะกัน มีเรื่องขุ่นหมองใจ ไพ่ใบนี้จะปัดเป่าสิ่งเหล่านั้นไป ก็จะมีความเข้าใจกัน สิ่งที่ขุ่นมัวก็จะได้รับการแก้ไขสะสาง\n\nไพ่ใบนี้ถ้ามองในแง่ไม่ดีก็อาจต้องดูจากสถานการณ์ครับ ถ้าสถานการณ์เป็นไปในแบบที่ยืดเยื้อ อีกฝ่ายคบหลายคน หรือไม่ชัดเจน ไพ่ใบนี้จะเป็นไพ่ที่เปิดเผยสิ่งเหล่านั้นออกมา ซึ่งทำให้เราเข้าใจเค้า รู้เรื่องของเค้า ถ้ามันแย่เราก็จะตัดสินใจได้ชัดเจนแล้วว่าเราจะเอายังไงต่อ ที่ดีกับใจของเรา\n\nนอกจากนี้ยังสามารถบ่งบอกถึงการที่จะมีลูกได้ด้วยครับ\n\nKEYWORD ของ ไพ่ยิปซี ใบนี้จึงคือ\n''ความสัมพันธ์ที่มีความหวังอันสดใส ความชัดเจน การเปิดเผย...\"");
        jTextPane2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(jButton1))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPane2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane2AncestorAdded
        jTextPane1.setEditable(false);
    }//GEN-LAST:event_jTextPane2AncestorAdded

    private void jTextPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane1AncestorAdded
        jTextPane2.setEditable(false);
    }//GEN-LAST:event_jTextPane1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a19().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
