/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;

/**
 *
 * @author ASUS
 */
public class a2 extends javax.swing.JFrame {

    /**
     * Creates new form a2
     */
    public a2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        setIconImages(null);
        setSize(new java.awt.Dimension(1280, 760));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\โปรเจค\\OOP\\src\\oop\\2.png")); // NOI18N

        jTextPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        jTextPane1.setFont(new java.awt.Font("TH Niramit AS", 0, 24)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(153, 102, 0));
        jTextPane1.setText("THE MAGICIAN\n\"จอมเวทย์ผู้มีความสามารถในการเชื่อมระหว่างโลกและจักรวาล ผู้มีเข้าใจในธรรมชาติและความสามารถในการควบคุมผสาน สรรสร้าง ทุกสรรพสิ่งจาก ดิน น้ำ ลม ไฟ\"");
        jTextPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        jTextPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 1, true));
        jTextPane2.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jTextPane2.setText("ไพ่ใบนี้บ่งบอกลักษณะของคนที่มีความรู้ ความสามารถ ฉลาด เข้าใจโลก เป็นนักวิชาการ นักวิจัย  แต่ในอีกมุมนึงก็อาจจะดูเป็นคนที่พูดดี พูดเก่ง มีความรู้ มากเกินกว่าที่จะเป็นปฏิบัติจริง\n\nความหมายในเรื่องความรัก\nไพ่ใบนี้ถ้ามองในมุมมองความสัมพันธ์ ถือว่าเป็นไพ่ที่ดีมากใบนึงครับ หมายถึงความรัก ความสัมพันธ์ที่จักรวาลเปิดทางให้ ยังไงยังงั้น เพราะทุกอย่างดูจะดีไปหมดในทุกๆด้าน ทั้งอารมณ์และความคิด หากมีความไม่เข้าใจกันก็จะทำการปรับความเข้าใจกันได้อย่างดี\n\nแต่ในมุมมองของถ้าเป็นตัวบุคคล อาจจะมีความแตกต่างซักเล็กน้อยต้องข้อเสียของจอมเวทย์คนนี้ เพราะคนๆนี้ที่ได้ไพ่ใบนี้เป็นตัวแทนนั้น จะมีลักษณะฉลาด เข้าใจทุกอย่าง และในความสัมพันธ์เค้าอาจจะใช้ Trick หรือ วิธีในความสัมพันธ์ที่ออกจะไม่ซื่อซักหน่อย \nแต่ก็ไม่ใช่สิ่งไม่ดี เช่น ถ้าจีบก็อาจจะมีการหายไปให้เราคิดถึงบ้างล่ะ มีการวางแผน ในการพัฒนาความสัมพันธ์ และคนๆนี้ก็อาจจะพูดเก่งแต่ไม่ปฏิบัติอะไรเลยก็เป็นได้ อาจเหมือนคนที่ดีแต่ปากได้ เพราะคนๆนี้เป็นพวกทฤษฎีเต็มหัว คือสามารถปฏิบัติและแสดงได้\n แต่ก็ไม่ทำให้เห็นซักที\n\nKEYWORD ของ ไพ่ยิปซี ใบนี้จึงคือ\n''คนที่มีความรู้ความสามารถ\nเข้าใจทุกสิ่งอย่างในความสัมพันธ์...''");
        jTextPane2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPane2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane2AncestorAdded
        jTextPane1.setEditable(false);
    }//GEN-LAST:event_jTextPane2AncestorAdded

    private void jTextPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane1AncestorAdded
        jTextPane2.setEditable(false);
    }//GEN-LAST:event_jTextPane1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
