/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;

/**
 *
 * @author ASUS
 */
public class a20 extends javax.swing.JFrame {

    /**
     * Creates new form a20
     */
    public a20() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(1332, 728));
        setSize(new java.awt.Dimension(1280, 760));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/20.png"))); // NOI18N

        jTextPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 0)));
        jTextPane1.setFont(new java.awt.Font("TH Niramit AS", 0, 24)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(102, 51, 0));
        jTextPane1.setText("JUDGEMENT\n\"วันพิพากษา เหล่าผู้วายชนม์ที่ลุกขึ้นมาเพื่อรอฟังเสียงแตรของเทพกาเบรียลในวันพิพากษา ใครจะได้ขึ้นสวรรค์ ใครจะตกนรกขึ้นอยู่กับสิ่งที่ได้ทำมา\"");
        jTextPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        jTextPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 153, 0)));
        jTextPane2.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(153, 51, 0));
        jTextPane2.setText("ไพ่ใบนี้ความหมายของมันคือก็จะคล้ายๆ ทำดีได้ดี ทำชั่วได้ชั่ว ครับ มันถึงเวลาที่ดวงชะตาจะเปลี่ยนแปลงแล้ว คล้ายไพ่หมายเลข 10 Wheel of Fortune  เพียงแต่ไพ่ใบนี้คือสิ่งที่รอคอย สิ่งที่คั่งค้าง มันจะถึงเวลาสะสางแล้วครับ กรรมในอดีต กรรมในปัจจุบัน จะได้รับการตัดสินแล้ว บางสิ่งบางอย่างกำลังจะจบลง และเริ่มต้นใหม่ไปในทางที่ผลกรรมที่เราได้ทำไว้\n\nตัวไพ่ยังหมายถึงการเปิดเผย สิ่งที่ถูกเก็บไว้ สิ่งที่ค้างคาใจ ก็จะได้รับการเปิดเผยสะสาง\n\nความหมายในเรื่องความรัก\nในด้านความรัก ไพ่ใบนี้มักหมายถึง การตัดสินใจ ถึงเวลาที่คุณจะตัดสินใจเลือกแล้วว่า ความสัมพันธ์นี้ดีหรือไม่ดี มันโอเคมั้ย ถ้าไม่ก็อาจถึงเวลาที่ต้องตัดสินใจ การตัดสินใจก็ขึ้นอยู่กับคุณที่คุณจะประเมินล่ะครับ\n\nแต่ทว่าแน่นอนไพ่ใบนี้มักจะมีการประกาศแจ้ง (ดังเช่นเสียงแตรในไพ่) จะมีการพูดคุยกัน จะมีการเคลียร์กัน ว่าอะไรดีไม่ดี สิ่งที่สะสมอยู่ในใจ สิ่งที่เก็บไว้สงสัยก็จะได้รับการเปิดเผย สะสาง เพื่อตัดสินใจที่จะอยู่ต่อหรือจากไป\n\nถ้าคุณถามว่าเค้ารู้สึกยังไงกับเราก็เช่นเดียวกัน ว่าเค้าก็กำลังตัดสินคุณอยู่ กำลังดูคุณอยู่ว่า คุณดีแค่ไหน คุณมีอะไรไม่ดีอยู่ เพื่อที่เค้าจะตัดสินใจ\n\nถ้าขึ้นเป็นตำแหน่งแนะนำก็ให้ เราทำดีที่สุดในความสัมพันธ์นี้ครับ เพราะผลลัพธ์มันก็ขึ้นอยู่กับการกระทำเรานั่นเอง\n\nKEYWORD ของ ไพ่ยิปซี ใบนี้จึงคือ\n''การตัดสิน ทำดีได้ดี ทำชั่วได้ชั่ว การจบของสิ่งๆนึงเพื่อเริ่มต้นใหม่...\"");
        jTextPane2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(jButton1))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPane2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane2AncestorAdded
        jTextPane1.setEditable(false);
    }//GEN-LAST:event_jTextPane2AncestorAdded

    private void jTextPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane1AncestorAdded
        jTextPane2.setEditable(false);
    }//GEN-LAST:event_jTextPane1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a20.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a20.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a20.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a20.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a20().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
