/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;

/**
 *
 * @author ASUS
 */
public class a21 extends javax.swing.JFrame {

    /**
     * Creates new form a21
     */
    public a21() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(1332, 728));
        setSize(new java.awt.Dimension(1280, 760));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/21.png"))); // NOI18N

        jTextPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 0)));
        jTextPane1.setFont(new java.awt.Font("TH Niramit AS", 0, 24)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(153, 51, 0));
        jTextPane1.setText("THE WORLD\n\"หญิงสาวที่เต้นระบำอยู่บนฟ้าอย่างร่าเริง โดยมีวงแหวนแห่งความสำเร็จล้อมรอบอยู่  สัญลักษณ์ตรงมุมทั้งสี่มุม แทนธาตุทั้งสี่ธาตุและหมายถึงไพ่ทั้งสี่ชนิด เหรียญ ไม้ ดาบ ถ้วย\"");
        jTextPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        jTextPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 102, 0)));
        jTextPane2.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(153, 51, 0));
        jTextPane2.setText("ไพ่ใบนี้เป็นไพ่ใบสุดท้ายในชุด Major Arcana ซึ่งก็หมายความว่าเป็นไพ่ที่จบสิ้น สมบูรณ์ ในทุกๆอย่าง มีอิสระและหลุดพ้นจากพันธนาการต่างๆแล้ว ซึ่งดูจากสีหน้าของหญิงสาวบนไพ่ก็พบว่าเธอเต้นรำอย่างมีความสุขและมีอิสระจากพันธนาการทั้งปวง\n\nนอกจากนี้ไพ่ใบนี้ยังหมายถึง อารมณ์ที่เราพอใจ สภาพจริงๆมันอาจไม่ได้ดีมาก แต่เราพอใจ พอเพียง ไม่มีอะไรต้องกังวลในสถานการณ์ที่เกิดขึ้น\n\nและไพ่ใบนี้อาจหมายถึงการเดินทางไปต่างประเทศ ไปดูโลกกว้างได้อีกด้วย\n\nความหมายในเรื่องความรัก\nความหมายของไพ่ใบนี้คือความรักอันสมบูรณ์ เรียกได้ว่าไม่ได้มีอะไรหวือหวา ไม่ได้มีอะไรแปลกประหลาด พวกคุณสองคนรักกันดี ซึ่งแค่นี้ก็เพียงพอแล้วสำหรับความสัมพันธ์\n\nหากคุณกำลังคบๆดูใจกัน ไพ่นี้ก็เป็นไปในทางที่ดีเช่นกันว่า ทุกอย่างกำลังจะลงตัวจนถึงขั้นตกลงปลงใจเป็นแฟนกันได้... แต่ทว่า ไพ่ใบนี้ต้องดูองค์ประกอบให้ดีว่า ถ้าผู้ชายถามว่า ผู้หญิงคิดยังไงกับเรา หรือสถานการณ์เป็นยังไงแล้ว ไพ่ใบนี้แทนฝ่ายหญิงล่ะก็ อาจแปลได้ว่า ผู้หญิงคนนี้ ยังลัลล้า มีความสุขด้วยตัวคนเดียวได้อยู่ อาจจะยังไม่เลือกใครก็ได้ ซึ่งทั้งนี้ทั้งนั้นต้องดูไพ่ประกอบอื่นๆ\n\nในกรณีที่ความสัมพันธ์ที่ไม่ค่อยดี ก็อาจจะได้มีการพูดคุยเคลียร์สะสาง เรื่องราวต่างๆที่ค้างคาใจให้จบสมบูรณ์ เพื่อพัฒนาไปเป็นความสัมพันธ์ที่ลงตัวขึ้นและดีกับใจครับ\n\nKEYWORD ของ ไพ่ยิปซี ใบนี้จึงคือ\n''ความสุข ความพอใจ ความพอเพียง การสมบูรณ์ในความสัมพันธ์...\"");
        jTextPane2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(jButton1))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPane2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane2AncestorAdded
        jTextPane1.setEditable(false);
    }//GEN-LAST:event_jTextPane2AncestorAdded

    private void jTextPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane1AncestorAdded
        jTextPane2.setEditable(false);
    }//GEN-LAST:event_jTextPane1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a21().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
