/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;

/**
 *
 * @author ASUS
 */
public class a3 extends javax.swing.JFrame {

    /**
     * Creates new form a3
     */
    public a3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(1332, 728));
        setSize(new java.awt.Dimension(1280, 760));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\โปรเจค\\OOP\\src\\oop\\3.png")); // NOI18N

        jScrollPane2.setViewportView(jTextPane2);

        jTextPane4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 0)));
        jTextPane4.setFont(new java.awt.Font("TH Niramit AS", 0, 24)); // NOI18N
        jTextPane4.setForeground(new java.awt.Color(153, 102, 0));
        jTextPane4.setText("THE EMPRESS\n\"จักรพรรดินีผู้เลอโฉม และมีความเป็นแม่สูง นั่งอยู่สวนป่าที่มีความอุดมสมบูรณ์ เธอพร้อมที่จะหล่อเลี้ยงและให้กำเนิดสรรพสิ่ง พร้อมที่จะดูแลคนของเธอเป็นอย่างดี\"");
        jTextPane4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane4AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane4.setViewportView(jTextPane4);

        jTextPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        jTextPane1.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(153, 102, 0));
        jTextPane1.setText("ไพ่ใบนี้ส่วนใหญ่ถ้าคนเป็นคู่กันแล้ว ก็อาจจะหมายความถึงการให้กำเนิดลูก ถ้าใครรอมีลูกหรือถามเรื่องมีลูก แล้วออกไพ่ใบนี้ขึ้นมา ก็มีแววจะตั้งครรภ์ได้ล่ะครับ\n\nความหมายในเรื่องความรัก\nไพ่ใบนี้ความหมายในด้านความรักค่อนข้างดีทีเดียวครับ เป็นความรักที่อุดมสมบูรณ์ ราบรื่น เรียกได้ว่าพร้อมให้กำเนิดสิ่งใหม่ๆชื่นมื่นโดยเฉพาะถ้าเป็นไพ่แทนตัวผู้หญิงด้วยแล้ว มันหมายถึงว่า \nอีกฝ่ายนั้นมอบใจและกายให้คุณจนหมด โดยที่คุณไม่ได้ควบคุมอะไร เค้ามองคุณเหมือน จักรพรรดินี ที่อยู่สูงทีเดียว จะเสียก็แต่บางทีเค้าอาจจะมองคุณอยู่สูงเกินไป แต่คุณก็ดูแลเค้าได้เป็นอย่างดี\nในกรณีที่ผู้ชายถามถึงว่าผู้หญิงคนนี้คิดยังไงกับตนแล้วได้ไพ่ใบนี้โผล่ขึ้นมาต้องบอกว่าเธอรู้ว่าคุณยอมเธอหมดใจเลยล่ะครับ เธอรู้ว่าเธอมีค่าสำหรับคุณ ซึ่งคุณก็รู้เรื่องนี้ดี แต่ก็ไม่ใช่ว่าพอรู้แล้วจะ\nเล่นตัวอะไร เพราะเธอมีลักษณะความเป็นแม่สูงคือเธอก็จะดูแลคุณอย่างดีตอบแทนความรักที่คุณมอบให้อย่างดีเหมือนกันถ้าจะเสียก็อาจตรงที่เธอคนนี้ค่อนข้างจะดูแลทุกคน\nได้ทั่วถึงเหมือนกันเธอสามารถแบ่งปันความรักการดูแลให้ทุกคนได้ ดังนั้นมันจึงบอกได้ยากว่าเธอจะชอบคุณหรือไม่ เธอจะมีคนอื่นมั้ย อยู่เหมือนกันครับ\n\nKEYWORD ของ ไพ่ยิปซี ใบนี้จึงคือ\n''ความเป็นแม่สูง ดูแลอย่างดีสมบูรณ์ คนที่เข้ามารักเธอจะยอมเธอทั้งกายและใจ...''");
        jTextPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 993, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap(439, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane1AncestorAdded
        jTextPane1.setEditable(false);
    }//GEN-LAST:event_jTextPane1AncestorAdded

    private void jTextPane4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane4AncestorAdded
        jTextPane2.setEditable(false);
    }//GEN-LAST:event_jTextPane4AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane4;
    // End of variables declaration//GEN-END:variables
}
