/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;

/**
 *
 * @author ASUS
 */
public class a5 extends javax.swing.JFrame {

    /**
     * Creates new form a5
     */
    public a5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(1332, 728));
        setSize(new java.awt.Dimension(1280, 760));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/5.png"))); // NOI18N

        jTextPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 51)));
        jTextPane1.setFont(new java.awt.Font("TH Niramit AS", 0, 24)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(102, 51, 0));
        jTextPane1.setText("THE HIEROPHANT\n\"สังฆราช ผู้ศึกษาความรู้ ธรรมเนียมปฏิบัติ เป็นผู้นำด้านความเชื่อ ความศรัทธา ผู้เคร่งครัดในจารีตพร้อมที่จะถ่ายทอดความรู้ความเชื่อให้เหล่าศิษย์ทั้งหลาย\"");
        jTextPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        jTextPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 153, 0)));
        jTextPane2.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(153, 102, 0));
        jTextPane2.setText("ไพ่ใบนี้เป็นลักษณะของไพ่ที่บ่งบอกถึงอะไรที่เป็นข้อตกลงร่วม เป็นกฏ เป็นประเพณี จารีต ที่ประพฤติตาม รวมถึงความเชื่อและศาสนา\nถ้าพูดถึงลักษณะคน ก็จะเป็นได้ทั้งพระ บาทหลวง ไปยันถึง ครูอาจารย์ ผู้สั่งสอน ผู้อบรมให้ความรู้ต่างๆ หรืออาจเป็นคนที่ประพฤติตนตามจารีต เป็นคนอนุรักษ์นิยม ทำตามสิ่งที่เรียนรู้มา ไม่นอกกรอบ\nพิธีกรรมต่างๆทางศาสนา และรวมถึงงานแต่งงานที่มีพิธีกรรมต่างๆ ไพ่ใบนี้ก็สามารถให้ความหมายเช่นนั้นได้\n\nความหมายในเรื่องความรัก\nไพ่ใบนี้ในด้านความรัก หมายถึงการมีข้อตกลงซึ่งกันและกัน ต่างฝ่ายที่ต่างมีวิธีคิด แนวคิดในความสัมพันธ์ที่ต่างกัน มาคุยกันเพื่อตกลงแนวคิดด้านความสัมพันธ์ร่วมกัน เช่น\nตกลงว่าจะรักกันแบบเป็นแฟนกันตกลงกันว่าเป็นแค่เพื่อนกันตกลงกันว่าเราจะคบกันแบบไม่มีความสัมพันธ์ที่ชัดเจน\nจะเป็นความสัมพันธ์แบบไหนต้องดูบริบทไพ่ใบอื่นประกอบเพื่อดูทิศทางว่าความสัมพันธ์จะเป็นในทางไหน แต่โดยปกติ ไพ่ใบนี้ไม่ใช่ไพ่ที่เน้นไปในทางความรักเท่าไหร่ ดังนั้นถ้าไพ่ใบนี้ใบเดียว มักจะแปลว่าความรักแบบเพื่อนมากกว่า ตัดสินใจเป็นเพื่อนไปก่อน คุยไปก่อน เพื่อดูความเข้ากันได้ ยังไม่ลงเอยเป็นแฟนกัน ซึ่งแต่ละฝ่ายก็ตกลงยินยอมในข้อตกลงนั้น\nแต่ถ้าหากเป็นแฟนกันแล้ว ไพ่ใบนี้อาจหมายถึงการตกลงปลงใจแต่งงานกันได้ครับ โดยเฉพาะทางฝั่งตะวันตก หรือประเทศที่แต่งงานโดยเข้าโบสถ์โดยปกติแล้ว จะมีความหมายเช่นนี้ได้ครับ\nในมุมมองของคน อาจหมายถึงคนที่เป็นอาจารย์ ครู ผู้อบรม ที่ปรึกษา หรือคนที่ชอบสั่งสอนให้ความรู้คนได้ครับ\n\nKEYWORD ของ ไพ่ยิปซี ใบนี้จึงคือ\n''ข้อตกลง แนวคิด ความเชื่อที่วางร่วมกันในความสัมพันธ์...''");
        jTextPane2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPane2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane2AncestorAdded
        jTextPane1.setEditable(false);
    }//GEN-LAST:event_jTextPane2AncestorAdded

    private void jTextPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane1AncestorAdded
        jTextPane2.setEditable(false);
    }//GEN-LAST:event_jTextPane1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
