/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;

/**
 *
 * @author ASUS
 */
public class a6 extends javax.swing.JFrame {

    /**
     * Creates new form a6
     */
    public a6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(1332, 728));
        setSize(new java.awt.Dimension(1280, 760));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/6.png"))); // NOI18N

        jTextPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 51)));
        jTextPane1.setFont(new java.awt.Font("TH Niramit AS", 0, 24)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(153, 51, 0));
        jTextPane1.setText("THE LOVERS\n\"เรื่องราวของอดัม กับ อีฟ ในสวนอีเดน ที่พระเจ้าได้ให้ทั้งคู่เป็นคู่ครองกันและอยู่อย่างมีความสุข แต่งูก็ได้เสนอผลไม้แห่งความรู้ซึ่งเป็นผลไม้ต้องห้ามที่พระเจ้าได้ห้ามไว้  ถึงทางเลือกที่พวกเขาจะต้องเลือก\"");
        jTextPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        jTextPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        jTextPane2.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(153, 102, 0));
        jTextPane2.setText("ไพ่ใบนี้ชื่ออาจเหมือนความรัก ความสมหวัง แต่อันที่จริงแล้ว ไพ่ใบนี้คือทางเลือก ถ้าดูจากรูปบนไพ่ จะเห็นว่า เทวดาได้ทำให้คนสองคนมาเจอกัน เปรียบเหมือนพรหมลิขิต แต่ก็ยังไม่ได้ตัดสินใจอะไรชัดเจนขึ้นมา เพราะถ้าดูจะเห็นว่า ฝ่ายหญิง หรือ อีฟ มองหน้าเทวดราเหมือนสงสัยว่า \"ผู้ชายคนนี้ใช่จริงๆรึเปล่า\" ดังนั้นไพ่ใบนี้จึงเปรียบเสมือนโอกาสที่เข้ามา ซึ่งเราต้องเลือกและตัดสินใจ\n\nความหมายในเรื่องความรัก\nไพ่ใบนี้จากชื่อไพ่ก็จะดูเน้นเรื่องความรักโดยตรงอยู่แล้วโดยตัวของมัน เป็นไพ่แห่งพรหมลิขิตที่ทำให้เราได้พบเจอคนที่ใช่ เข้ากันได้ดี มีความชอบซึ่งกันและกัน เหมือนมีด้ายแดงแห่งพรหมลิขิตผูกคนสองคนไว้ \nไพ่เหมือนจะดีทุกอย่างในด้านความรัก เพียงแต่ว่า มันมีจุดที่เป็น ทางเลือก\n\nแน่นอนว่าไพ่ใบนี้พอเป็นทางเลือก ก็เหมือนเป็นจุดที่เรายังตัดสินใจไม่ได้ ยังลังเลตัดสินใจยาก อาจหมายถึง\n\nยังไม่แน่ใจในตัวคนที่เข้ามา จึงไม่สามารถตัดสินใจได้\nคุยหลายคนแล้วมีตัวเลือก ไม่สามารถเลือกได้\nมีคนเข้ามาเป็นตัวเลือกในขณะที่มีแฟนอยู่แล้ว หรือก็คือการนอกใจนั่นเอง\nไพ่ใบนี้จึงหมายถึง รักสามเส้า การนอกใจ หรือเราเข้าไปอยู่เป็นตัวเลือกของเค้า ได้ด้วยครับ ซึ่งอันที่จริงต้องดูบริบทของไพ่ประกอบด้วยครับ\n\nKEYWORD ของ ไพ่ยิปซี ใบนี้จึงคือ\n''โอกาส โชคชะตาที่เข้ามา ซึ่งเป็นทางเลือกที่ต้องเลือก...''");
        jTextPane2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPane2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane2AncestorAdded
        jTextPane1.setEditable(false);
    }//GEN-LAST:event_jTextPane2AncestorAdded

    private void jTextPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane1AncestorAdded
        jTextPane2.setEditable(false);
    }//GEN-LAST:event_jTextPane1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
