/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;

/**
 *
 * @author ASUS
 */
public class a7 extends javax.swing.JFrame {

    /**
     * Creates new form a7
     */
    public a7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(1280, 728));
        setSize(new java.awt.Dimension(1280, 760));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/7.png"))); // NOI18N

        jTextPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));
        jTextPane1.setFont(new java.awt.Font("TH Niramit AS", 0, 24)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(153, 102, 0));
        jTextPane1.setText("THE CHARIOT\n\"อัศวินรถม้าผู้ที่สามารถควบคุมรถม้าไปได้ด้วยพละกำลัง พร้อมมุ่งหน้าเข้าประจันข้าศึก โดยไม่เกรงกลัวต่อสิ่งใด \"");
        jTextPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        jTextPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 102, 0)));
        jTextPane2.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(153, 102, 0));
        jTextPane2.setText("ความหมายของไพ่ใบนี้จะเป็นไพ่แห่งการเคลื่อนที่ การมุทะลุ เพื่อไปให้ถึงชัยชนะ ดังนั้นไพ่นี้จึงเปรียบเสมือนไพ่ที่พร้อมออกศึกเพื่อชัยชนะ แม้ยังไม่รู้ว่าตัวเองจะชนะหรือไม่ แต่ก็พร้อมลุยไปข้างหน้าด้วยความสามารถทั้งหมดที่มี...\n\nถ้าให้เปรียบเหมือนการเจอสิ่งกีดขวาง คนอื่นคงหักหลบ แต่อัศวินรถไม้ ไม่!! เขาจะพุ่งชนไปตรงๆให้สิ่งกีดขวางหรือ กำแพงพังไป\n\nลักษณะของคนที่เป็นอัศวินรถม้านั้น จะเป็นคนที่ค่อนข้าง มุทะลุ ดุดัน และดื้อในความคิดของตัวเองและแนวทางของตัวเอง แต่ก็เป็นคนที่เชื่อฟังคำสั่งของคนที่ตัวเองเคารพยอมรับได้ดีอีกด้วย\n\nความหมายในเรื่องความรัก\nในทางความรักไพ่ใบนี้ เป็นได้ทั้งดีและไม่ดี ขึ้นกับไพ่รอบๆและบริบทในความสัมพันธ์  แต่หลักๆคือการมุทะลุ ใช้ความมุ่งมั่นเดินหน้าในความสัมพันธ์ อาจแปลได้ในหลายๆแบบ เช่น\n\nเค้าไม่สนใจคุณ แต่คุณก็ยังตั้งใจเดินหน้าจีบต่อไป\nคู่รักที่เข้ากันไม่ได้ แต่ก็ยังฝืนๆคบกันต่อไป\nคนที่เลิกกันก็มีความมุ่งมั่นที่จะเดินหน้าจากกันไปในเส้นทางที่ตัดสินใจแล้ว\nถ้าหมายถึงคนก็หมายถึงคนๆนั้นมีความมุ่งมั่นมุทะลุที่จะเข้าหา จีบ ไปยันถ้าตัดสินใจจะถอย จะเท ก็จะไปอย่างชัดเจนเลยทีเดียว ไพ่ใบนี้จึงค่อนข้างมีคำแปลที่สับสนในทิศทาง จำเป็นต้องดูไพ่ใบอื่นประกอบครับ\n\nแต่โดยปกติไพ่ใบนี้ถือว่าค่อนข้างดี เพราะหมายถึงการเดินทางไปออกรบ นำไปสู่ชัยชนะ และอาจหมายถึงความรักที่เดินหน้าต่อไป โดยไม่กลัวอุปสรรคใดๆทั้งสิ้น\nไพ่ใบนี้อาจแปลได้ถึงการเดินทาง หรือบุคคลที่มาจากที่ห่างไกลได้ด้วยยครับ\n\nKEYWORD ของ ไพ่ยิปซี ใบนี้จึงคือ\n''ความมุ่งมั่น ความมุทะลุ ในความสัมพันธ์ ที่สามารถควบคุมได้...''");
        jTextPane2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPane2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane2AncestorAdded
        jTextPane1.setEditable(false);
    }//GEN-LAST:event_jTextPane2AncestorAdded

    private void jTextPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane1AncestorAdded
        jTextPane2.setEditable(false);
    }//GEN-LAST:event_jTextPane1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
