/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;

/**
 *
 * @author ASUS
 */
public class a8 extends javax.swing.JFrame {

    /**
     * Creates new form a8
     */
    public a8() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(1332, 728));
        setSize(new java.awt.Dimension(1280, 760));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/8.png"))); // NOI18N

        jTextPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        jTextPane1.setFont(new java.awt.Font("TH Niramit AS", 0, 24)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(153, 51, 0));
        jTextPane1.setText("STRENGTH\n\"หญิงสาวลูบหัวและคางของสิงโตด้วยใบหน้ายิ้มอย่างสงบ ซึ่งสิงโตก็ยอมเธอ โดยที่เธอไม่จำเป็นต้องออกแรงใดๆ\"");
        jTextPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        jTextPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));
        jTextPane2.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(102, 0, 0));
        jTextPane2.setText("ไพ่ใบนี้ความหมายเปรียบเหมือนความเข้มแข็งที่เราสามารถควบคุมภายในจิตใจ สามารถต้านทานความดุดัน ความโกรธ ความดิบเถื่อนซึ่งเปรียบเสมือนสิงโตในตัวเองลงได้ เพราะนั้นคือความแข็งแกร่งที่แท้จริง\n\nไพ่ใบนี้ถ้าเป็นตำแหน่งแทนตัวบุคคลจะหมายถึง คนที่มีความเข้มแข็งแบบ อ่อนนอก แข็งใน ข้างในจิตใจเข้มแข็ง อ่อนโยนแต่ไม่อ่อนแอ\n\nอาจหมายถึงการที่เรามีความเข้มแข็ง สามารถเอาชนะอุปสรรคปัญหาต่างๆได้อย่างดีอีกด้วยครับ\nความหมายในเรื่องความรัก\nไพ่ใบนี้ในด้านความรัก ก็ถือเป็นความรักที่เข้มแข็งและไม่แพ้อุปสรรคอะไรง่ายๆ ถ้าหากมีการทะเลาะเบาะแว้งกันก็สามารถควบคุมอารมณ์และเข้าใจกันได้ง่าย สามารถพัฒนาเป็นความสัมพันธ์ระยะยาวที่ดีได้อีกด้วยครับ\n\nในกรณีที่ไพ่ใบนี้แทนบุคคลที่เป็นผู้หญิง  ก็จะหมายความว่าผู้หญิงคนนี้ เป็นผู้หญิงที่มีเสน่ห์ น่าหลงใหล ดูบริสุทธิ์ น่าปกป้อง แต่ก็สามารถทำให้ผู้ชายของเธอ หรือคนที่เธอคุย ยอมสยบได้โดยง่าย เปรียบเสมือน ราชสีห์ที่ยอมสยบต่อกระต่ายน้อย ยังไงยังงั้น\n\nหากไพ่ใบนี้แทนตำแหน่งผู้ชาย ก็ไม่ต่างกันครับ ก็จะเป็นฝ่ายชายที่ยอมสยบต่อฝ่ายหญิง แม้ตัวเองจะแข็งแกร่ง ดุแค่ไหนก็ตาม ก็จะหงอต่อหน้าผู้หญิงคนนี้\n\nไพ่ใบนี้ ในความสัมพันธ์ที่ยังไม่ชัดเจน หรือพึ่งเริ่มต้น อาจหมายถึงการที่เราต้องคอยควบคุมความรู้สึกรักที่รุนแรงภายในใจตัวเองไว้ ไม่ให้มันล้นเกิน จนทำให้อีกฝ่ายอึดอัดได้อีกด้วยครับ\n\nKEYWORD ของ ไพ่ยิปซี ใบนี้จึงคือ\n''ความเข้มแข็งในการควบคุมจิตใจ ผู้หญิงคนนึงทำให้ผู้ชายยอมสยบได้...''");
        jTextPane2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPane2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane2AncestorAdded
        jTextPane1.setEditable(false);
    }//GEN-LAST:event_jTextPane2AncestorAdded

    private void jTextPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane1AncestorAdded
        jTextPane2.setEditable(false);
    }//GEN-LAST:event_jTextPane1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
