/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;

/**
 *
 * @author ASUS
 */
public class a9 extends javax.swing.JFrame {

    /**
     * Creates new form a9
     */
    public a9() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(1332, 728));
        setSize(new java.awt.Dimension(1280, 760));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/9.png"))); // NOI18N

        jTextPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 102)));
        jTextPane1.setFont(new java.awt.Font("TH Niramit AS", 0, 24)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(153, 102, 0));
        jTextPane1.setText("THE HERMIT\n\"นักพรตผู้ออกเดินทางปลีกวิเวกขึ้นเขาไปเพียงลำพัง ค้นหาตัวเอง และเพื่อมองโลกในมุมที่กว้างกว่า\"");
        jTextPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        jTextPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 51)));
        jTextPane2.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(153, 51, 0));
        jTextPane2.setText("ไพ่ใบนี้เปรียบเสมือน นักพรต ที่ออกค้นหาตัวเอง ค้นหาคำตอบที่เราตามหา หรืออาจไปถึงเรื่องการเข้าถึงเรื่องจิตวิญญาณของตัวเอง\n\nถ้าคนที่มีไพ่ใบนี้เป็นตัวแทน ก็หมายถึงคนที่ค่อนข้างจะแยกตัวออกจากสังคม เป็นคนที่แยกตัวออกไป เพื่อจะค้นหาตัวเอง หาคำตอบบางอย่าง หรือมองปัญหาในมุมกว้าง อาจหมายถึง พระ นักบวช ฤาษี ที่ปลีกวิเวก ธุดงค์ ก็เป็นได้ครับ\nความหมายในเรื่องความรัก\nไพ่ใบนี้ด้านความรัก ส่วนใหญ่จะแปลถึงความโสด ถ้าถามว่าคนๆนั้นมีใครรึยัง คิดยังไง ก็อาจหมายความได้ว่า เค้าโสด เค้ายังไม่อยากมีใคร หรือไม่เค้ายังออกค้นหาตัวเอง ยังออกไปตามเป้าหมายของชีวิตอยู่\n\nถ้าเป็นความรักที่เป็นเป็นคู่รัก หรือเป็นแฟนกันแล้วอาจหมายความว่า ความรักเริ่มถดถอย ความรู้สึกต่างๆเริ่มหายไป จนน่าจะออกห่างกันซักพัก เพื่อให้ต่างฝ่ายได้คิดได้ไตร่ตรองดูอีกที เพราะบางทีการที่อยู่ด้วยกันมากเกินไปก็อาจจะทำให้เกิดการละเลยกันได้ครับ การห่างกันเพื่อให้ได้เห็นว่าจริงๆแล้ว ข้างในเรารู้สึกยังไง เป็นลักษณะเหมือน ห่างกันซักพัก จึงเปรียบเสมือนความหมายของไพ่ใบนี้ได้ครับ\n\nถ้าคนโสดถามเรื่องความรัก ก็ต้องอาจบอกว่า อาจจะยังไม่มีคนที่ใช้เข้ามา อาจจะต้องค้นหามองหาต่อไป แต่มันไม่ใช่จะไม่มีความหวัง เพราะเราถือตะเกียงแห่งดวงดาวที่เปรียบเสมือนความหวังอยู่ เพียงแต่ยังไม่ใช่ช่วงเวลาที่จะมีเข้ามาครับ\n\n \n\nKEYWORD ของ ไพ่ยิปซี ใบนี้จึงคือ\n''การแยกตัวออกมาคนเดียว ออกจากสถานการณ์บางอย่าง เพื่อค้นหาคำตอบด้วยมุมมองที่กว้างขึ้น...''");
        jTextPane2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 934, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPane2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane2AncestorAdded
        jTextPane1.setEditable(false);
    }//GEN-LAST:event_jTextPane2AncestorAdded

    private void jTextPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane1AncestorAdded
        jTextPane2.setEditable(false);
    }//GEN-LAST:event_jTextPane1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
